### ISSUE TITLE
Deprecation warning in Google Chrome

### ISSUE THREAD

**Issue by ajithpmohan** [anseki/polyfill-svg-uri#3]
polyfill-svg-uri.min.js:1 [Deprecation] 'webkitURL' is deprecated. Please use 'URL' instead.

polyfill-svg-uri.min.js:1 [Deprecation] 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.

Please help.
Thanks in Advance

**Comment by anseki** [comment]
Hi @ajithpmohan, thank you for the comment.
No problem because that is warnings not errors. That is correct behavior.

**Comment by anseki** [comment]
No reply came. I close this issue.
