### ISSUE TITLE
DOMException: Failed to read the 'cssRules'

### ISSUE THREAD

**Issue by yarilchenko** [anseki/polyfill-svg-uri#4]
@anseki Hello. I had faced with some problem:
> DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules

Error in `parseRule` function.

I get this error in case when I have a link for external resources (like google fonts).
This problem related to browser CORS policy. I've fixed this problem locally with using of `try/catch` block, but I not sure that this fix is the better option.

Would you make updates, please?
Or I can create PR with my fix :)

**Comment by anseki** [comment]
Hi @yarilchenko, thank you for the report.
Could you show me an example code to reproduce the problem?

**Comment by yarilchenko** [comment]
@anseki ofc. Just add this one link:
`<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Fira+Sans">`

**Comment by anseki** [comment]
I see.
That has no relation with the CORS.
I will fix it soon.

**Comment by yarilchenko** [comment]
@anseki thank you.
